#!/usr/bin/env bash
#
# Release a Node package. 

# @author: Daniel Souza <me@posix.dev.br>
# @license: MIT

# Text Decorators
reset="\e[0m"
strong="\e[1;39m"
red="\e[1;31m"
yellow="\e[1;33m"
green="\e[1;32m"
blue="\e[1;34m"

# Strict Mode
# exit when a command has a non-zero exit status
set -e

# check number of args
if [ "$#" -ne 1 ]; then
  printf "${red}ERROR:${reset} %s\n" "Illegal number of parameters"
fi

# Main
printf "${blue}NOTICE:${reset} %s\n" "Building assets..." 
npm run build && git add "dist/" && git commit -m "Build distributables for v${1}"

# FIXME: As building occurs prior to versioning distributable has the previous version.

printf "\n${blue}NOTICE:${reset} %s\n" "Versioning..."
npm version "$1"

printf "\n${blue}NOTICE:${reset} %s\n" "Pushing to Git repository..."
git push && git push origin "v${1}"

printf "\n${blue}NOTICE:${reset} %s\n" "Publishing to NPM repository..."
npm publish

printf "\n${green}DONE:${reset} %s\n" "Released!" 
